version: "3.9"

services:
  api:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - db
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGO_URI: ${MONGO_URI}
    networks:
      - invoice

  client:
    restart: on-failure
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - api
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - invoice

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8080:3000"
    volumes:
      - static_volume:/app/staticfiles
      - pdf_volume:/app/docs
    depends_on:
      - api
    networks:
      - invoice

networks:
  invoice:
    driver: bridge

volumes:
  static_volume:
  pdf_volume: